[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utf8-decode = "1.0.1"
more-asserts="0.2.2"
walkdir="2"
bitvec="1"
